name: aayu
description: Child nutrition tracker for Sri Lankan parents
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.3.0
  
  # Local Storage
  sqflite: ^2.3.3
  shared_preferences: ^2.3.2
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  lottie: ^3.1.3
  table_calendar: ^3.1.2
  
  # Utilities
  intl: 0.20.2
  path_provider: ^2.1.4
  path: ^1.9.0
  connectivity_plus: ^6.0.5
  image_picker: ^1.1.2
  url_launcher: ^6.2.4
  
  # Security
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: NotoSerifSinhala
      fonts:
        - asset: assets/fonts/NotoSerifSinhala-Regular.ttf
        - asset: assets/fonts/NotoSerifSinhala-Bold.ttf
          weight: 700